apiVersion: v1
kind: Namespace
metadata:
  name: sales-system

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: sales
  namespace: sales-system

spec:
  selector:
    matchLabels:
      app: sales

  template:
    metadata:
      labels:
        app: sales

    spec:
      terminationGracePeriodSeconds: 60

      containers:
      - name: sales-api
        image: service-image
        resources:
          requests:
            cpu: "250m"
            memory: "36Mi"
          limits:
            cpu: "250m"
            memory: "36Mi"

       