apiVersion: v1
kind: Namespace
metadata:
  name: sales-system
---

### Jaeger

---
apiVersion: v1
kind: Service
metadata:
  name: jaeger-service
  namespace: sales-system
spec:
  type: ClusterIP
  selector:
    app: jaeger
  ports:
    - name: http-jaeger
      port: 16686
      targetPort: http-jaeger
